# Generated by Django 4.1.4 on 2022-12-18 10:37

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('icon', models.ImageField(upload_to='job_icon', verbose_name='Ikonka')),
            ],
            options={
                'verbose_name': 'Ish turi',
                'verbose_name_plural': 'Ish turlari',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Ismi')),
                ('image', models.ImageField(upload_to='team', verbose_name='Rasm')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobtype', verbose_name='Ish turi')),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': "Jamoa a'zolari",
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='Rasm')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Haqida')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('on_top', models.BooleanField(default=False, verbose_name='Tepadami?')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.service', verbose_name='Servis')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='blog', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('views_count', models.IntegerField(default=0, verbose_name="Ko'rilganlar soni")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
            },
        ),
    ]
