# Generated by Django 4.1.4 on 2022-12-20 16:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Haqida'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Haqida'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Haqida'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Ismi'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Ismi'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Ismi'),
        ),
    ]
