# Generated by Django 4.1.4 on 2022-12-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_body_en_blog_body_ru_blog_body_uz_blog_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='job_type_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobtype', verbose_name='Ish turi'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='job_type_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobtype', verbose_name='Ish turi'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='job_type_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobtype', verbose_name='Ish turi'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='Kontent'),
        ),
    ]
