# Generated by Django 4.1.4 on 2022-12-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='service',
            name='body_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='service',
            name='body_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='service',
            name='body_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
    ]
